- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - fail2ban
      - ufw
      - vim
      - curl
      - git
      - python3-pip
      - unzip

- name: Configure fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Allow SSH through UFW
  ufw:
    rule: allow
    port: "22"
    proto: tcp