- name: Add SSH public key
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ ssh_public_key }}"
    state: present
  when: ssh_public_key is defined

- name: Configure SSH security
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart ssh